### ISSUE TITLE
Missing data through getTaxiData() method

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-flightstats-source#6]
@trong-le @aloisbarreras 

Looking at the taxi_arrivals table off of getTaxiData() and getUniqueTaxiData() methods, it seems like we're missing a LOT of fields (taxiinminutes, blockminutes, airminutes, taxioutminutes, scheduledtaxiinminutes) that look available when I query the API directly.

What might be happening is that some data (actual taxi time vs. scheduled) only becomes available hours after it occurred...if that's the case, then we may need to drop the table and just have the query cycle through the last twelve hours to get the most recent status.

**Comment by benjamingregory** [comment]
@trong-le @aloisbarreras Can you two decide on what to do with this? If it's not an issue we can replicate right now, lets make a note of it and close, but we shouldn't be in the practice of ignoring issues.

**Comment by ryw** [comment]
will not fix
