### ISSUE TITLE
Default option to pull all fields

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-flightstats-source#9]
Pass in a `true/false` config value to pull in all available fields. If `true`, iterate through all fields and pull everything in. If `false`, look for and pull in specifically requested array of fields.

**Comment by benjamingregory** [comment]
@trong-le @aloisbarreras 

Was this resolved?

**Comment by benjamingregory** [comment]
@trong-le ...?

**Comment by benjamingregory** [comment]
New scope: Follow example of Salesforce where all fields are requested by default if inclusion/exclusion fields are empty.
https://github.com/aries-data/aries-activity-salesforce-source

**Comment by ryw** [comment]
will not fix
